master:
  ip: "10.24.24.75"
  port: 36000
  username: "mayankarya"
  password: "mayankorin7"
  work_dir: "/media/ssd/AgentMesh"
  python_env: "/home/mayankarya/distributed/"
  hf_cache: "/media/ssd/huggingface_cache"


workers:
  - ip: "10.24.24.74"
    username: "mayankarya"
    password: "mayankorin6"
    work_dir: "/media/ssd/AgentMesh"
    python_env: "/home/mayankarya/distributed/"
    hf_cache: "/media/ssd/huggingface_cache"

  - ip: "10.24.24.49"
    username: "mayankarya"
    password: "mayankagx5"
    work_dir: "/media/ssd/AgentMesh"
    python_env: "/home/mayankarya/distributed/"
    hf_cache: "/media/ssd/huggingface_cache"
